# fly.toml app configuration file generated for icaad-fragrant-forest-5283 on 2024-12-17T22:01:02-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icaad-fragrant-forest-5283'
primary_region = 'ord'

[build]
  image = 'flyio/hellofly:latest'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
