# fly.toml app configuration file generated for icaad-dark-forest-1718 on 2025-01-17T20:06:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icaad-dark-forest-1718'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'myapp_data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
